import assert from 'assert';

import { Day } from '../src/days/day6';
import { parseInput } from '../src/utils/input';

const testInput = parseInput(`....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`);

const test2 = parseInput(`...........#.....#......
...................#....
...#.....##.............
......................#.
..................#.....
..#.....................
....................#...
........................
.#........^.............
..........#..........#..
..#.....#..........#....
........#.....#..#......`);

describe('Day 6', ()=>{
  it('should run part 1', ()=>{
    assert.equal(Day.part1(testInput),41);
  });
  it('should run part 2', ()=>{
    assert.equal(Day.part2(test2),19);
  });
});