import assert from 'assert';

import { Day } from '../src/days/day8';
import { parseInput } from '../src/utils/input';

const testInput = parseInput(`............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`);

describe('Day 8', ()=>{
  it('should run part 1', ()=>{
    assert.equal(Day.part1(testInput),14);
  });
  it('should run part 2', ()=>{
    assert.equal(Day.part2(testInput),34);
  });
});